### ISSUE TITLE
Rapport logo design

### ISSUE THREAD

**Issue by reallinfo** [ricn/rapport#4]
Hello!

Would you like me to design a logo that looks elegant in the readme file for Rapport? Actually, I have an idea. I'd like to hear it if you have an idea.

**Comment by ricn** [comment]
Sure, that would be cool :-)

**Comment by reallinfo** [comment]
Oh, okey. How is these? If you like it, i will send a pr.

![rapport](https://user-images.githubusercontent.com/36298335/41498613-8d269df6-717a-11e8-9722-e1f91f8ecf84.jpg)

**Comment by ricn** [comment]
I like them, especially those with a capital letter just in the beginning.

**Comment by reallinfo** [comment]
Oh, okay. then I will send you a pr.  If you want something special, please tell me.

**Comment by ricn** [comment]
Merged. Thanks!
